[[cells]]
name = "ckb-passport-lock"
enable_type_id = true
location = { file = "build/release/ckb-passport-lock" }

[[cells]]
name = "rsa_sighash_all"
enable_type_id = false
location = { file = "ckb-miscellaneous-scripts/build/rsa_sighash_all" }

# Dep group cells
[[dep_groups]]
name = "dep_group"
cells = [
  "ckb-passport-lock",
  "rsa_sighash_all",
]

# Replace with your own lock if you want to unlock deployed cells. 
# The lock here is just an example.
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x0000000000000000000000000000000000000000"
hash_type = "type"

