[package]
name = "ckb-passport-lock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7.1"
ckb-lib-iso97962-rsa = { path = "../../ckb-lib-iso97962-rsa" }
blake2b-ref = "0.1"