[package]
name = "ckb-lib-iso97962-rsa"
version = "0.1.0"
authors = ["dylan <duanyytop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7.1"
